---
plugins:
  - jekyll-remote-theme

remote_theme: nrandecker/particle   # Will this work? Will I need to build and deploy first?

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
